sudo: required

language: python

services:
  - docker

before_install:
    - docker build -t ccbot .   
    - docker run --entrypoint=/bin/echo ccbot /bin/sh -c "./cover.sh"

script:
  - ./cover.sh

